project:
  type: website
  output-dir: docs          # Required for GitHub Pages

website:
  title: "Woo-Sung Hollenhorst"
  favicon: images/favicon.svg
  navbar:
    logo: images/logo.svg
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects/index.qmd
        text: Projects
      - href: reflection.qmd
        text: Reflection
      - href: contact.qmd
        text: Contact
    right:
      - text: CV
        href: cv/cv.pdf
        target: _blank
      - icon: globe
        href: travels.html
      - icon: github
        href: https://github.com/woosunghollenhorst
        target: _blank
  page-footer:
    center: "Woo-Sung Hollenhorst | E-Portfolio"

format:
  html:
    theme: darkly
    css: styles.scss